# -*- coding: utf-8 -*-
"""Lab2  - Limpieza de Datos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TTnFQcq5eXaC3760Us6FqTPe0zx8_hUH

# Presentación-Importación de Librerias y Carga de datos
"""

#Importar libreria
import pandas as pd

#Visualizar datos del dataframe
pd.read_csv('sonic_aprendisaje(Matrices).csv')

"""# Análisis exploratorio de datos"""

# Carga de datos en una variable
sonic_games = pd.read_csv('sonic_aprendisaje(Matrices).csv') 
#Visualizacion de variables nulas y sus tipos de datos
sonic_games.info()

#Observacion del valor máximo en una escala superior a los demás valores.
sonic_games.describe().T

"""#Limpieza de Datos

Validar cuántos datos nulos existen:
"""

#Valores nulos por columna
missing_values_count  = sonic_games.isna().sum()
#Guardar suma de valores nulos en variable "missing_values_count"
missing_values_count

#Al verificar la lista, no existen valores nulos.

"""Eliminar Datos Duplicados"""

df= pd.DataFrame(sonic_games)
df

dx= df[(df.B==0)&
       (df.A==0)&
       (df.MODE==0)&
       (df.START==0)&
       (df.UP==0)&
       (df.DOWN==0)&
       (df.LEFT==0)&
       (df.RIGTH==0)&
       (df.C==0)&
       (df.Y==0)&
       (df.X==0)&
       (df.Z==0)&
       (df.REWARD==0)
]
dx

from google.colab import drive
drive.mount('/content/drive')